apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment
spec:
  selector:
    matchLabels:
      app: mpd
  replicas: 2
  template:
    metadata:
      labels:
        app: mpd
    spec:
      containers:
      - name: mpd
        image: abdullahkhabir/music:alpine
        # comment it out if your image is hosted on docker hub or some other 
        # registry. If you have image locally available, it will use it.
        #imagePullPolicy: Never
        ports:
        - containerPort: 6600
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  selector:
    app: mpd
  ports:
    - name: for-mpc
      protocol: TCP
      port: 7777
      targetPort: 6600
    - name: for-web
      protocol: TCP
      port: 8090
      targetPort: 8000
  type: LoadBalancer
