apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  selector:
    app: mpd
  ports:
    - name: for-mpc
      protocol: TCP
      port: 7777
      targetPort: 6600
    - name: for-web
      protocol: TCP
      port: 8090
      targetPort: 8000
  type: LoadBalancer

