apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30001
  selector:
    app: music-app

---
apiVersion: v1
kind: Pod
metadata:
  name: music-app-pod
  labels:
    app: music-app
spec:
  containers:
    - name: music-container
      image: abdullahkhabir/music

